SRC = main.c gapmis_cpu.c gapmis_gpu.c
OBJ = $(SRC:.c=.o)
CC  = gcc
CFLAGS = -g -Wall -I$(HOME)/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/ -D_USE_GPU -msse3 -O3 -fomit-frame-pointer -funroll-loops -lOpenCL 

all: main

main: $(OBJ)
	$(CC) $(CFLAGS) -o $@ $(OBJ) 

clean:
	rm -f main $(OBJ) *~ 

$(OBJ) : EDNAFULL.h EBLOSUM62.h gapmis.h errors.h Makefile.GPU

