SRC = main.c gapmis_cpu.c
OBJ = $(SRC:.c=.o)
CC  = gcc
CFLAGS = -Wall -msse3 -O3 -fomit-frame-pointer -funroll-loops  

all: main

main: $(OBJ)
	$(CC) $(CFLAGS) -o $@ $(OBJ) 

clean:
	rm -f main $(OBJ) *~ 

$(OBJ) : EDNAFULL.h EBLOSUM62.h gapmis.h errors.h Makefile.CPU
