SRC = gapmis.c
OBJ = $(SRC:.c=.o)
CC  = gcc

CFLAGS = -g -Wall -I$(HOME)/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/ -D_USE_GPU -msse3 -O -fomit-frame-pointer -funroll-loops -lOpenCL 

all: gapmis

gapmis: $(OBJ)
	$(CC) $(CFLAGS) -o $@ $(OBJ)

clean:
	rm -f gapmis $(OBJ) *~ 

$(OBJ) : EDNAFULL.h EBLOSUM62.h gapmis.h errors.h Makefile.GPU

